### ISSUE TITLE
When would there be code release

### ISSUE THREAD

**Issue by amy-cao** [KinglittleQ/pitch-net#1]
Hi,

PitchNet is really awesome work! When will you release the code?

**Comment by KinglittleQ** [comment]
This work was done while I was interning at Tencent AI Lab. Now I've left Tencent so I have no access right to the source code now. Sorry about that.

**Comment by KinglittleQ** [comment]
Hey, here is an unofficial implementation I found: https://github.com/learn2lean/PitchNet

**Comment by amy-cao** [comment]
Thanks!

**Comment by Lukelluke** [comment]
What  a pity!

BTW, could release your implement of paper "Unsupervised Singing Voice Conversion" for BaseLine comparing use?

That would be nice if u could offer any help!
